[tool.poetry]
name = "adapters"
version = "0.1.0"
description = ""
authors = ["mablin7 <magyarb0201@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^5.4.1"
cotypes = {path = "../cotypes", develop = true}
GitPython = {version = "^3.1.24", optional = true}

[tool.poetry.dev-dependencies]
pyfakefs = "^4.5.1"
ipython = "^7.27.0"

[tool.poetry.extras]
git_driver = ["GitPython"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
