[tool.poetry]
name = "api_server"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
cotypes = {path = "../cotypes", develop = true}
adapters = {path = "../adapters", develop = true}
uvicorn = "^0.14.0"
fastapi = "^0.66.0"
sqlalchemy = ">=1.4,<1.4.23"
databases = {extras = ["sqlite"], version = "^0.5.2"}
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]
manager = {path = "../manager", develop = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

