services:
  postgres:
    image: postgres:15.1
    env_file: [ .env ]
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5000:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-api-test:
    env_file: [ .env ]
    build:
      context: ./
      dockerfile: ./services/auth_api/tests/Dockerfile-test
      args:
        PORT: 6999
    ports:
      - "6999:6999"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services/auth_api:/src/services/auth_api
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

version: '3.7'