services:

  frontend:
    env_file: [ .env.dev.local ]
    build:
      context: ./
      dockerfile: ./services/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./services/frontend:/src
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

  postgres:
    image: postgres:15.1
    env_file: [ .env.dev.local ]
    restart: always
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5001:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-api:
    env_file: [ .env.dev.local ]
    build:
      context: ./
      dockerfile: ./services/auth_api/Dockerfile
      args:
        PORT: 6099
    ports:
      - "6099:6099"
    volumes:
      - ./services/auth_api:/src/services/auth_api
      - ./database:/src/database
      - ./apiconfig:/src/apiconfig
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

  distributions-api:
    env_file: [ .env.dev.local ]
    build:
      context: ./
      dockerfile: ./services/distributions_api/Dockerfile
      args:
        DREAM_ROOT_PATH: /dream
        PORT: 6098
    depends_on:
      - auth-api
    ports:
      - "6098:6098"
    volumes:
      - ./services/distributions_api:/src/services/distributions_api
      - ./database:/src/database
      - ./apiconfig:/src/apiconfig
      - ~/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

version: '3.7'
