services:

  testrunner:
    env_file: [ .env ]
    build:
      context: ./
      dockerfile: ./tests/backend/Dockerfile
    depends_on:
      - distributions-api
    deploy:
      resources:
        limits:
          memory: 256M
