# generated by datamodel-codegen:
#   filename:  component.json
#   timestamp: 2021-10-03T17:23:34+00:00

from __future__ import annotations

from pydantic import BaseModel


class Component(BaseModel):
    id: int
    type: str
    label: str
    group: str
    template_link: str
