# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2021-10-03T17:23:34+00:00

from __future__ import annotations

from typing import Any, Dict

from pydantic import BaseModel


class Data(BaseModel):
    id: int
    type: str
    content: Dict[str, Any]
