[tool.poetry]
name = "cotypes"
version = "0.1.0"
description = ""
authors = ["mablin7 <magyarb0201@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
datamodel-code-generator = "^0.11.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
