# apis expose 698* ports
services:

  frontend:
    env_file: [ ../.envs/.env.stage ]
    build:
      context: ../..
      dockerfile: ./services/frontend/Dockerfile
      args:
        FRONTEND_ENV: stage
    ports:
      - "6981:5173"
    volumes:
      - ../../services/frontend:/src
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

  postgres:
    image: postgres:15.1
    env_file: [ ../.envs/.env.stage ]
    restart: always
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "6980:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-api:
    env_file: [ ../.envs/.env.stage ]
    build:
      context: ../..
      dockerfile: ./services/auth_api/Dockerfile
      args:
        PORT: 6999
    ports:
      - "6989:6999"
    volumes:
      - ../../services/auth_api:/src/services/auth_api
      - ../../database:/src/database
      - ../../apiconfig:/src/apiconfig
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

  distributions-api:
    env_file: [ ../.envs/.env.stage ]
    build:
      context: ../..
      dockerfile: ./services/distributions_api/Dockerfile
      args:
        DREAM_ROOT_PATH: /dream
        PORT: 6998
    depends_on:
      - auth-api
    ports:
      - "6988:6998"
    volumes:
      - ../../services/distributions_api:/src/services/distributions_api
      - ../../database:/src/database
      - ../../apiconfig:/src/apiconfig
      - ~/.aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M

version: '3.7'
