export const consts = {
  IS_PREVIEW_MODE: 'IS_PREVIEW_MODE',
  IS_TABLE_VIEW: 'VIEW_TABLE',
  LEFT_SIDEPANEL_IS_ACTIVE: 'LEFT_SIDEPANEL_IS_ACTIVE',
  RIGHT_SIDEPANEL_IS_ACTIVE: 'RIGHT_SIDEPANEL_IS_ACTIVE',
  BREADCRUMBS_PATH: 'BREADCRUMBS_PATH',
  EDITOR_ACTIVE_TAB: 'EDITOR_ACTIVE_TAB',
  ACTIVE_ASSISTANT: 'ACTIVE_ASSISTANT',
}
