export const consts = {
  IS_PREVIEW_MODE: 'IS_PREVIEW_MODE',
  IS_TABLE_VIEW: 'VIEW_TABLE',
  LEFT_SP_IS_ACTIVE: 'LEFT_SP_IS_ACTIVE',
  RIGHT_SP_IS_ACTIVE: 'RIGHT_SP_IS_ACTIVE',
  BREADCRUMBS_PATH: 'BREADCRUMBS_PATH',
  EDITOR_ACTIVE_TAB: 'EDITOR_ACTIVE_TAB',
  ACTIVE_ASSISTANT: 'ACTIVE_ASSISTANT',
  SKILL_EDITOR_IS_ACTIVE: 'SKILL_EDITOR_IS_ACTIVE',
  COPILOT_SP_IS_ACTIVE: 'COPILOT_SP_IS_ACTIVE',
  ACTIVE_ASSISTANT_SP_ID: 'ACTIVE_ASSISTANT_SP_ID',
  ACTIVE_SKILL_SP_ID: 'ACTIVE_SKILL_SP_ID',
  ACTIVE_ANNOTATOR_SP_ID: 'ACTIVE_ANNOTATOR_SP_ID',
}
