/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Position = "left" | "top" | "right" | "bottom";

export interface Flow {
  el: (
    | {
        id: string;
        position: Xyposition;
        targetPosition?: Position;
        sourcePosition?: Position;
        data?:
          | {
              selectedIntent: string;
                        }
          | {
              respStr: string;
                        }
          | {
              endpoint: string;
              method?: string;
              payload?: string;
                        };
            }
    | {
        id: string;
        source: string;
        target: string;
        sourceHandle?: string;
        targetHandle?: string;
            }
  )[];
}
export interface Xyposition {
  x: number;
  y: number;
}
