[tool.poetry]
name = "manager"
version = "0.1.0"
description = ""
authors = ["mablin7 <magyarb0201@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.7.9"
PyYAML = "^5.4.1"
minio = "^7.1.0"
api-types-py = {path = "../api_types_py", develop = true}
fastapi = "^0.68.0"
uvicorn = "^0.14.0"
aiohttp = "^3.7.4"
aiodocker = "^0.21.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
