[tool.poetry]
name = "manager"
version = "0.1.0"
description = ""
authors = ["mablin7 <magyarb0201@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
PyYAML = "^5.4.1"
aiohttp = "^3.7.4"
deeppavlov = {git = "https://github.com/deepmipt/DeepPavlov.git", rev = "rulebased_gobot"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
