# generated by datamodel-codegen:
#   filename:  component.json
#   timestamp: 2021-09-16T15:04:07+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class Component(BaseModel):
    class Config:
        extra = Extra.forbid

    type: str
    label: Optional[str] = None
