# generated by datamodel-codegen:
#   filename:  model.json
#   timestamp: 2021-09-16T15:04:07+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra


class Model(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
