# generated by datamodel-codegen:
#   filename:  training.json
#   timestamp: 2021-09-16T15:04:07+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Extra


class Status(Enum):
    RUNNING = 'RUNNING'
    FAILED = 'FAILED'
    SUCCESS = 'SUCCESS'


class Training(BaseModel):
    class Config:
        extra = Extra.forbid

    status: Status
