/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Training {
  id: number;
  timestamp: string;
  status: "RUNNING" | "FAILED" | "SUCCESS";
  template_link: string;
  trained_model_link?: string;
}
